import { createHash } from "node:crypto";
import { findAppSchema } from "../../core/src/index.js";
import type { ConfigIR, EntityIR, IntentIR, LocalizedText, ParameterIR } from "../../core/src/index.js";

export const GENERATED_SWIFT_FILE = "IntentLaneGenerated.swift";
export const ADAPTER_TEMPLATE_FILE = "IntentLaneAdapter.swift";
export const STRING_TABLE = "IntentLane";

const STRINGS_BANNER = "/* Generated by IntentLane. Do not edit. */";

const swiftString = (value: string): string => JSON.stringify(value);
const shortcutPhrase = (value: string): string => swiftString(value).replace(/\$\{appName\}/g, "\\(.applicationName)");
const defaultLocale = (ir: ConfigIR): string => ir.app.locales[0] ?? "en";
const localized = (values: LocalizedText, locale: string): string => values[locale] ?? values[Object.keys(values).sort()[0] ?? ""] ?? "";
const localizedResource = (value: string): string => `LocalizedStringResource(${swiftString(value)}, table: ${swiftString(STRING_TABLE)})`;
const usesSystemSchema = (ir: ConfigIR): boolean =>
  ir.entities.some((entity) => entity.schema !== undefined) ||
  ir.intents.some((intent) => intent.schema !== undefined);
const declaresMacOS27 = (ir: ConfigIR): boolean =>
  [ir.app.minMacos, ir.app.minIos].some((floor) => floor !== undefined && Number(floor.split(".")[0]) >= 27);
const macOS27Availability = (ir: ConfigIR): string =>
  usesSystemSchema(ir) || declaresMacOS27(ir) ? "@available(macOS 27.0, *)\n" : "";

const SWIFT_TYPES: Readonly<Record<string, string>> = {
  string: "String",
  integer: "Int",
  number: "Double",
  boolean: "Bool",
  date: "DateComponents",
  datetime: "Date",
  searchCriteria: "StringSearchCriteria"
};

const AUTHENTICATION_POLICIES: Readonly<Record<string, string>> = {
  none: ".alwaysAllowed",
  required: ".requiresAuthentication"
};

const SNIPPET_VIEW = `@available(macOS 13.0, iOS 16.0, *)
struct IntentLaneSnippetView: View {
  let title: LocalizedStringResource
  let fields: [(LocalizedStringResource, String)]

  var body: some View {
    VStack(alignment: .leading, spacing: 8) {
      Text(title).font(.headline)
      ForEach(fields.indices, id: \\.self) { index in
        HStack {
          Text(fields[index].0).foregroundStyle(.secondary)
          Spacer()
          Text(fields[index].1)
        }
      }
    }
    .padding()
  }
}`;

const pascalCase = (value: string): string => value.split("_").map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`).join("");

const labelsFor = (parameter: ParameterIR, value: string): LocalizedText => parameter.values?.[value] ?? {};

const parameterTitle = (parameter: ParameterIR, locale: string): string => (parameter.title ? localized(parameter.title, locale) : parameter.id);

function protocolOf(intent: IntentIR): "open" | "delete" | undefined {
  if (!intent.schema) return undefined;
  return findAppSchema("intent", intent.schema)?.protocol;
}

function targetEntity(ir: ConfigIR, intent: IntentIR): EntityIR {
  const entity = ir.entities.find((candidate) => candidate.id === intent.target);
  if (!entity) throw new Error(`IL1401: Intent '${intent.id}' names unknown target entity '${intent.target ?? ""}'.`);
  return entity;
}

function schemaParameterDeclarations(ir: ConfigIR, intent: IntentIR): readonly Readonly<{ name: string; swiftType: string }>[] {
  const entry = intent.schema ? findAppSchema("intent", intent.schema) : undefined;
  if (!entry || entry.parameters.length === 0) {
    return intent.parameters.map((parameter) => ({ name: parameter.id, swiftType: swiftType(intent, parameter, ir.entities) }));
  }
  return entry.parameters.map((parameter) => {
    const typeName = parameter.type === "entity" || parameter.type === "entityArray"
      ? `IntentLane${targetEntity(ir, intent).swiftName}Entity`
      : undefined;
    if (parameter.type === "entity") return { name: parameter.name, swiftType: typeName! };
    if (parameter.type === "entityArray") return { name: parameter.name, swiftType: `[${typeName!}]` };
    return { name: parameter.name, swiftType: SWIFT_TYPES[parameter.type] ?? "String" };
  });
}

function enumTypeName(intent: IntentIR, parameter: ParameterIR): string {
  return `IntentLane${intent.swiftName}${pascalCase(parameter.id)}`;
}

function swiftType(intent: IntentIR, parameter: ParameterIR, entities: readonly EntityIR[]): string {
  if (parameter.type === "enum") return enumTypeName(intent, parameter);
  if (parameter.type === "entity" || parameter.type === "entity_list") {
    const entity = entities.find((candidate) => candidate.id === parameter.entity);
    if (!entity) throw new Error(`IL1301: Entity parameter '${parameter.id}' references unknown entity '${parameter.entity ?? ""}'.`);
    const name = `IntentLane${entity.swiftName}Entity`;
    return parameter.type === "entity_list" ? `[${name}]` : name;
  }
  const mapped = SWIFT_TYPES[parameter.type];
  if (!mapped) throw new Error(`IL1301: Parameter '${parameter.id}' uses unsupported type '${parameter.type}'.`);
  return mapped;
}

function parameterDeclaration(intent: IntentIR, parameter: ParameterIR, entities: readonly EntityIR[], locale: string): string {
  const prompt = parameter.prompt ? `, requestValueDialog: IntentDialog(${localizedResource(localized(parameter.prompt, locale))})` : "";
  return `  @Parameter(title: ${localizedResource(parameterTitle(parameter, locale))}${prompt})\n  var ${parameter.id}: ${swiftType(intent, parameter, entities)}`;
}

function emitEntity(entity: EntityIR, locale: string, targeted: boolean, reindexable: boolean, spotlightIndexName: string, availability: string): string {
  const typeName = `IntentLane${entity.swiftName}Entity`;
  const resolverName = `IntentLane${entity.swiftName}Resolver`;
  const queryName = `IntentLane${entity.swiftName}Query`;
  const camelName = `${entity.swiftName.slice(0, 1).toLowerCase()}${entity.swiftName.slice(1)}`;
  const titleProperty = entity.displayTitle === entity.identifier ? "id" : entity.displayTitle;
  const subtitleProperty =
    entity.displaySubtitle === undefined
      ? undefined
      : entity.displaySubtitle === entity.identifier
        ? "id"
        : entity.displaySubtitle === entity.displayTitle
          ? titleProperty
          : entity.displaySubtitle;
  const names = ["id", titleProperty, ...(subtitleProperty === undefined ? [] : [subtitleProperty])];
  const properties = [...new Set(names)].map((name) => ({ name, optional: name === subtitleProperty && name !== titleProperty && name !== "id" }));
  const conformed = entity.schema !== undefined;
  const declarations = properties.map((property) => {
    const type = `String${property.optional ? "?" : ""}`;
    if (targeted && !conformed && property.name === titleProperty && property.name !== "id") {
      return `  @Property(title: ${localizedResource("Title")}, indexingKey: \\.title)\n  var ${property.name}: ${type}`;
    }
    return `  ${conformed ? "var" : "let"} ${property.name}: ${type}`;
  }).join("\n");
  const searchableTitle = "";
  const annotation = conformed
    ? `@AppEntity(schema: .${entity.schema})\n`
    : entity.exposure
      ? `@AppEntity(exposureCondition: .${entity.exposure.rules.map((rule) => rule.replace(/_([a-z])/g, (_, c) => c.toUpperCase())).join(", .")})\n`
      : "";

  const conformance = targeted ? "AppEntity, IndexedEntity" : "AppEntity";
  const typeDisplay = conformed
    ? ""
    : `  static var typeDisplayRepresentation: TypeDisplayRepresentation {\n    TypeDisplayRepresentation(name: ${localizedResource(localized(entity.title, locale))})\n  }\n\n`;
  const subtitleExpression =
    subtitleProperty === undefined
      ? ""
      : `,\n      subtitle: ${subtitleProperty === titleProperty || subtitleProperty === "id" ? `LocalizedStringResource(stringLiteral: ${subtitleProperty})` : `${subtitleProperty}.map { LocalizedStringResource(stringLiteral: $0) }`}`;
  const initializerProperties = targeted && !conformed
    ? [...properties.filter((property) => property.name !== titleProperty), ...properties.filter((property) => property.name === titleProperty)]
    : properties;
  const initializer = conformed || (targeted && !conformed)
    ? `\n  init(${properties.map((property) => `${property.name}: String${property.optional ? "?" : ""}`).join(", ")}) {\n${initializerProperties.map((property) => `    self.${property.name} = ${property.name}`).join("\n")}\n  }`
    : "";
  const queryConformance = targeted
    ? reindexable ? "EntityQuery, EntityStringQuery, IndexedEntityQuery" : "EntityQuery, EntityStringQuery"
    : "EntityQuery";
  const reindexing = reindexable
    ? `\n\n  func reindexEntities(for identifiers: [String], indexDescription: CSSearchableIndexDescription) async throws {\n    guard let resolver = await IntentLaneEntityResolvers.${entity.id} else { return }\n    let entities = try await resolver.${camelName}Entities(for: identifiers)\n    try await CSSearchableIndex(name: ${swiftString(spotlightIndexName)}).indexAppEntities(entities)\n  }\n\n  func reindexAllEntities(indexDescription: CSSearchableIndexDescription) async throws {\n    guard let resolver = await IntentLaneEntityResolvers.${entity.id} else { return }\n    let entities = try await resolver.suggested${entity.swiftName}Entities()\n    try await CSSearchableIndex(name: ${swiftString(spotlightIndexName)}).indexAppEntities(entities)\n  }`
    : "";
  const stringResolution = targeted
    ? `\n\n  func entities(matching string: String) async throws -> [${typeName}] {\n    guard let resolver = await IntentLaneEntityResolvers.${entity.id} else { return [] }\n    return try await resolver.${camelName}Entities(matching: string)\n  }`
    : "";
  const stringResolverRequirement = targeted
    ? `\n  func ${camelName}Entities(matching string: String) async throws -> [${typeName}]`
    : "";
  return `${availability}${annotation}struct ${typeName}: ${conformance} {\n${typeDisplay}  static let defaultQuery = ${queryName}()\n\n${declarations}${initializer}${searchableTitle}\n\n  var displayRepresentation: DisplayRepresentation {\n    DisplayRepresentation(\n      title: LocalizedStringResource(stringLiteral: ${titleProperty})${subtitleExpression}\n    )\n  }\n}\n\n${availability}protocol ${resolverName}: Sendable {\n  func ${camelName}Entities(for identifiers: [String]) async throws -> [${typeName}]${stringResolverRequirement}\n  func suggested${entity.swiftName}Entities() async throws -> [${typeName}]\n}\n\n${availability}struct ${queryName}: ${queryConformance} {\n  func entities(for identifiers: [String]) async throws -> [${typeName}] {\n    guard let resolver = await IntentLaneEntityResolvers.${entity.id} else { return [] }\n    return try await resolver.${camelName}Entities(for: identifiers)\n  }${stringResolution}\n\n  func suggestedEntities() async throws -> [${typeName}] {\n    guard let resolver = await IntentLaneEntityResolvers.${entity.id} else { return [] }\n    return try await resolver.suggested${entity.swiftName}Entities()\n  }${reindexing}\n}`;
}

function entityDeclarations(ir: ConfigIR, locale: string): string {
  if (ir.entities.length === 0) return "";
  const targeted = new Set(ir.intents.filter((intent) => protocolOf(intent) !== undefined).map((intent) => intent.target ?? ""));
  const reindexable = new Set(ir.intents.filter((intent) => intent.schema === "system.open").map((intent) => intent.target ?? ""));
  const entities = [...ir.entities].sort((left, right) => left.id.localeCompare(right.id));
  const registry = entities.map((entity) => `  static var ${entity.id}: (any IntentLane${entity.swiftName}Resolver)?`).join("\n");
  const availability = macOS27Availability(ir);
  return `${entities.map((entity) => emitEntity(entity, locale, targeted.has(entity.id), reindexable.has(entity.id), `${ir.app.id}.${entity.id}`, availability)).join("\n\n")}\n\n${availability}@MainActor\nenum IntentLaneEntityResolvers {\n${registry}\n}\n\n`;
}

function emitEnum(intent: IntentIR, parameter: ParameterIR, locale: string): string {
  const name = enumTypeName(intent, parameter);
  const values = Object.keys(parameter.values ?? {}).sort((left, right) => left.localeCompare(right));
  const cases = values.map((value) => `  case ${value}`).join("\n");
  const representations = values.map((value) => `    .${value}: DisplayRepresentation(title: ${localizedResource(localized(labelsFor(parameter, value), locale))})`).join(",\n");
  return `enum ${name}: String, AppEnum {\n${cases}\n\n  static var typeDisplayRepresentation: TypeDisplayRepresentation {\n    TypeDisplayRepresentation(name: ${localizedResource(parameterTitle(parameter, locale))})\n  }\n\n  static var caseDisplayRepresentations: [${name}: DisplayRepresentation] {\n    [\n${representations}\n    ]\n  }\n}`;
}

function enumDeclarations(ir: ConfigIR, locale: string): string {
  const declarations = ir.intents.flatMap((intent) => intent.parameters.filter((parameter) => parameter.type === "enum").map((parameter) => emitEnum(intent, parameter, locale)));
  return declarations.length === 0 ? "" : `${declarations.join("\n\n")}\n\n`;
}

function queryValue(intent: IntentIR, source: string): string {
  const type = intent.parameters.find((parameter) => parameter.id === source)?.type ?? "string";
  if (type === "integer" || type === "number") return `String(${source})`;
  if (type === "boolean") return `${source} ? "true" : "false"`;
  if (type === "datetime") return `${source}.ISO8601Format()`;
  if (type === "date") return `String(format: "%04d-%02d-%02d", ${source}.year ?? 0, ${source}.month ?? 0, ${source}.day ?? 0)`;
  if (type === "enum") return `${source}.rawValue`;
  if (type === "entity") return `${source}.id`;
  if (type === "entity_list") return `${source}.map { $0.id }.joined(separator: ",")`;
  return source;
}

function routeExpression(intent: IntentIR, scheme: string): string {
  const entries = Object.entries(intent.mapping).sort(([left], [right]) => left.localeCompare(right));
  if (entries.length === 0) return `IntentLaneRoute.make(scheme: ${swiftString(scheme)}, path: ${swiftString(intent.route)}, query: [:])`;
  const items = entries.map(([target, source]) => `${swiftString(target)}: ${queryValue(intent, source)}`).join(", ");
  return `IntentLaneRoute.make(scheme: ${swiftString(scheme)}, path: ${swiftString(intent.route)}, query: [${items}])`;
}

function authenticationLine(intent: IntentIR): string {
  const policy = intent.risk ? AUTHENTICATION_POLICIES[intent.risk.authentication] : undefined;
  return policy ? `\n  static let authenticationPolicy: IntentAuthenticationPolicy = ${policy}` : "";
}

function confirmationStatement(intent: IntentIR, locale: string): string {
  if (intent.risk?.confirmation !== "always") return "";
  const prompt = localized(intent.risk.confirmationPrompt ?? intent.title, locale);
  return `    try await requestConfirmation(actionName: .continue, dialog: IntentDialog(${localizedResource(prompt)}))\n`;
}

function nativeHandlerName(intent: IntentIR): string {
  if (!intent.handler) throw new Error(`IL1301: native intent '${intent.id}' has no handler.`);
  return intent.handler;
}

function openHandlerName(intent: IntentIR): string {
  return intent.handler ?? `${intent.swiftName}Handler`;
}

function nativeReturnType(ir: ConfigIR, intent: IntentIR): string | undefined {
  if (!intent.returns) return undefined;
  const entity = ir.entities.find((candidate) => candidate.id === intent.returns);
  if (!entity) throw new Error(`IL1301: Intent '${intent.id}' returns unknown entity '${intent.returns}'.`);
  return `IntentLane${entity.swiftName}Entity`;
}

function nativeHandlerDeclarations(ir: ConfigIR): string {
  const natives = ir.intents.filter((intent) => intent.mode === "native" && (intent.handler !== undefined || protocolOf(intent) === "open"));
  if (natives.length === 0) return "";
  const availability = macOS27Availability(ir);
  const protocols = natives.map((intent) => {
    const parameters = schemaParameterDeclarations(ir, intent).map((parameter) => `${parameter.name}: ${parameter.swiftType}`).join(", ");
    const returns = nativeReturnType(ir, intent);
    const handler = protocolOf(intent) === "open" ? openHandlerName(intent) : nativeHandlerName(intent);
    return `${availability}protocol ${handler}: Sendable {\n  func perform(${parameters}) async throws${returns ? ` -> ${returns}` : ""}\n}`;
  });
  const registry = natives.map((intent) => `  static var ${intent.id}: (any ${protocolOf(intent) === "open" ? openHandlerName(intent) : nativeHandlerName(intent)})?`).join("\n");
  return `${protocols.join("\n\n")}\n\n${availability}enum IntentLaneHandlerError: Error {\n  case missingHandler(String)\n}\n\n${availability}@MainActor\nenum IntentLaneIntentHandlers {\n${registry}\n}\n\n`;
}

function emitNativeIntent(ir: ConfigIR, intent: IntentIR, locale: string): string {
  const title = localized(intent.title, locale);
  const description = intent.description ? `\n  static let description = IntentDescription(${localizedResource(localized(intent.description, locale))})` : "";
  const authentication = authenticationLine(intent);
  const confirmation = confirmationStatement(intent, locale);
  const annotation = `${macOS27Availability(ir)}${intent.schema ? `@AppIntent(schema: .${intent.schema})\n` : ""}`;
  const parameters = intent.parameters.map((parameter) => parameterDeclaration(intent, parameter, ir.entities, locale)).join("\n\n");
  const dialog = intent.dialog ? localized(intent.dialog, locale) : title;
  const returns = nativeReturnType(ir, intent);
  const argumentsList = schemaParameterDeclarations(ir, intent).map((parameter) => `${parameter.name}: ${parameter.name}`).join(", ");
  const signature = `some IntentResult & ProvidesDialog${returns ? ` & ReturnsValue<${returns}>` : ""}`;
  const call = returns
    ? `    let value = try await handler.perform(${argumentsList})\n    return .result(value: value, dialog: IntentDialog(${localizedResource(dialog)}))`
    : `    try await handler.perform(${argumentsList})\n    return .result(dialog: IntentDialog(${localizedResource(dialog)}))`;
  return `${annotation}struct ${intent.swiftName}: AppIntent {\n  static let title: LocalizedStringResource = ${localizedResource(title)}${description}${authentication}\n\n${parameters}\n\n  func perform() async throws -> ${signature} {\n${confirmation}    guard let handler = await IntentLaneIntentHandlers.${intent.id} else {\n      throw IntentLaneHandlerError.missingHandler(${swiftString(intent.id)})\n    }\n${call}\n  }\n}`;
}

function emitProtocolIntent(ir: ConfigIR, intent: IntentIR, locale: string): string {
  const title = localized(intent.title, locale);
  const description = intent.description ? `\n  static let description = IntentDescription(${localizedResource(localized(intent.description, locale))})` : "";
  const authentication = authenticationLine(intent);
  const annotation = `${macOS27Availability(ir)}${intent.schema ? `@AppIntent(schema: .${intent.schema})\n` : ""}`;
  const typeName = `IntentLane${targetEntity(ir, intent).swiftName}Entity`;
  if (protocolOf(intent) === "open") {
    const handler = openHandlerName(intent);
    return `${annotation}struct ${intent.swiftName}: OpenIntent {\n  static let title: LocalizedStringResource = ${localizedResource(title)}${description}${authentication}\n\n  @Parameter(title: ${localizedResource(localized(targetEntity(ir, intent).title, locale))})\n  var target: ${typeName}\n\n  @MainActor\n  func perform() async throws -> some IntentResult {\n    guard let handler = IntentLaneIntentHandlers.${intent.id} else {\n      throw IntentLaneHandlerError.missingHandler(${swiftString(intent.id)})\n    }\n    try await handler.perform(target: target)\n    return .result()\n  }\n}`;
  }
  const dialog = intent.dialog ? localized(intent.dialog, locale) : title;
  return `${annotation}struct ${intent.swiftName}: AppIntent {\n  static let title: LocalizedStringResource = ${localizedResource(title)}${description}${authentication}\n\n  static var parameterSummary: some ParameterSummary {\n    Summary("Delete \\(\\.$entities)")\n  }\n\n  var entities: [${typeName}]\n\n  func perform() async throws -> some IntentResult & ProvidesDialog {\n    guard let handler = await IntentLaneIntentHandlers.${intent.id} else {\n      throw IntentLaneHandlerError.missingHandler(${swiftString(intent.id)})\n    }\n    try await handler.perform(entities: entities)\n    return .result(dialog: IntentDialog(${localizedResource(dialog)}))\n  }\n}`;
}

function emitSchemaIntent(ir: ConfigIR, intent: IntentIR, locale: string): string {
  const title = localized(intent.title, locale);
  const description = intent.description ? `\n  static let description = IntentDescription(${localizedResource(localized(intent.description, locale))})` : "";
  const authentication = authenticationLine(intent);
  const annotation = `${macOS27Availability(ir)}${intent.schema ? `@AppIntent(schema: .${intent.schema})\n` : ""}`;
  const parameters = schemaParameterDeclarations(ir, intent);
  const criteriaTypealias = intent.schema === "system.searchInApp" ? "\n  typealias Criteria = StringSearchCriteria" : "";
  const declarations = parameters.map((parameter) => `  @Parameter(title: ${localizedResource(parameter.name)})\n  var ${parameter.name}: ${parameter.swiftType}`).join("\n\n");
  const argumentsList = parameters.map((parameter) => `${parameter.name}: ${parameter.name}`).join(", ");
  const dialog = intent.dialog ? localized(intent.dialog, locale) : title;
  return `${annotation}struct ${intent.swiftName}: AppIntent {\n  static let title: LocalizedStringResource = ${localizedResource(title)}${description}${authentication}${criteriaTypealias}\n\n${declarations}\n\n  func perform() async throws -> some IntentResult & ProvidesDialog {\n    guard let handler = await IntentLaneIntentHandlers.${intent.id} else {\n      throw IntentLaneHandlerError.missingHandler(${swiftString(intent.id)})\n    }\n    try await handler.perform(${argumentsList})\n    return .result(dialog: IntentDialog(${localizedResource(dialog)}))\n  }\n}`;
}

function schemaDeclaresParameters(intent: IntentIR): boolean {
  if (!intent.schema) return false;
  const entry = findAppSchema("intent", intent.schema);
  return (entry?.parameters.length ?? 0) > 0;
}

function emitIntent(ir: ConfigIR, intent: IntentIR, locale: string, scheme: string): string {
  if (protocolOf(intent)) return emitProtocolIntent(ir, intent, locale);
  if (schemaDeclaresParameters(intent)) return emitSchemaIntent(ir, intent, locale);
  if (intent.mode === "native") return emitNativeIntent(ir, intent, locale);
  const title = localized(intent.title, locale);
  const description = intent.description ? `\n  static let description = IntentDescription(${localizedResource(localized(intent.description, locale))})` : "";
  const authentication = authenticationLine(intent);
  const confirmation = confirmationStatement(intent, locale);
  const annotation = `${macOS27Availability(ir)}${intent.schema ? `@AppIntent(schema: .${intent.schema})\n` : ""}`;
  const parameters = intent.parameters.map((parameter) => parameterDeclaration(intent, parameter, ir.entities, locale)).join("\n\n");
  const dialog = intent.dialog ? localized(intent.dialog, locale) : title;
  const fields = intent.parameters.map((parameter) => `(${localizedResource(parameterTitle(parameter, locale))}, ${queryValue(intent, parameter.id)})`).join(", ");
  return `${annotation}struct ${intent.swiftName}: AppIntent {\n  static let title: LocalizedStringResource = ${localizedResource(title)}${description}${authentication}\n\n${parameters}\n\n  func perform() async throws -> some IntentResult & ProvidesDialog & ShowsSnippetView & OpensIntent {\n${confirmation}    let intentLaneURL = ${routeExpression(intent, scheme)}\n    return .result(\n      opensIntent: OpenURLIntent(intentLaneURL),\n      dialog: IntentDialog(${localizedResource(dialog)}),\n      view: IntentLaneSnippetView(title: ${localizedResource(title)}, fields: [${fields}])\n    )\n  }\n}`;
}

function emitShortcuts(ir: ConfigIR, locale: string): string {
  const registered = ir.intents
    .map((intent) => ({ intent, phrases: intent.phrases[locale] ?? [] }))
    .filter(({ phrases }) => phrases.length > 0);
  if (registered.length === 0) return "";
  const providers = registered.map(({ intent, phrases }) => `      AppShortcut(intent: ${intent.swiftName}(), phrases: [\n${phrases.map((phrase) => `        ${shortcutPhrase(phrase)}`).join(",\n")}\n      ], shortTitle: ${localizedResource(localized(intent.title, locale))}, systemImageName: "sparkles")`);
  return `struct IntentLaneShortcuts: AppShortcutsProvider {\n  static var appShortcuts: [AppShortcut] {\n${providers.join("\n")}\n  }\n}`;
}

export function generateSwift(ir: ConfigIR): string {
  const locale = defaultLocale(ir);
  const enums = enumDeclarations(ir, locale);
  const entities = entityDeclarations(ir, locale);
  const handlers = nativeHandlerDeclarations(ir);
  const intents = ir.intents.map((intent) => emitIntent(ir, intent, locale, ir.app.urlScheme)).join("\n\n");
  const shortcuts = emitShortcuts(ir, locale);
  const spotlight = ir.intents.some((intent) => protocolOf(intent) !== undefined) ? "import CoreSpotlight\n" : "";
  const shortcutsSection = shortcuts ? `\n\n${shortcuts}` : "";
  return `// Generated by IntentLane. Do not edit.\n// Source schema: ${ir.schemaVersion}\n\nimport AppIntents\nimport Foundation\n${spotlight}import SwiftUI\n\nenum IntentLaneRoute {\n  static func make(scheme: String, path: String, query: [String: String]) -> URL {\n    var components = URLComponents()\n    components.scheme = scheme\n    components.path = path\n    if !query.isEmpty {\n      components.queryItems = query.sorted { $0.key < $1.key }.map { URLQueryItem(name: $0.key, value: $0.value) }\n    }\n    return components.url ?? URL(string: "about:blank")!\n  }\n}\n\n${SNIPPET_VIEW}\n\n${enums}${entities}${handlers}${intents}${shortcutsSection}\n`;
}

export function generateAdapterTemplate(ir: ConfigIR): string {
  const targets = ir.entities
    .filter((entity) => ir.intents.some((intent) => intent.target === entity.id && protocolOf(intent) !== undefined))
    .sort((left, right) => left.id.localeCompare(right.id));
  const searches = ir.intents.filter((intent) => intent.schema === "system.searchInApp" && intent.handler !== undefined);
  const opens = ir.intents.filter((intent) => protocolOf(intent) === "open");
  if (targets.length === 0 && searches.length === 0) {
    throw new Error("IL1501: An adapter template needs a system schema intent with a target entity or a search handler.");
  }
  const blocks = targets.map((entity) => {
    const typeName = `IntentLane${entity.swiftName}Entity`;
    const resolverName = `IntentLane${entity.swiftName}Resolver`;
    const implementationName = `IntentLane${entity.swiftName}ResolverImplementation`;
    const camelName = `${entity.swiftName.slice(0, 1).toLowerCase()}${entity.swiftName.slice(1)}`;
    return `actor ${implementationName}: ${resolverName} {
  func ${camelName}Entities(for identifiers: [String]) async throws -> [${typeName}] {
    // TODO: Map stable application identifiers to ${typeName} values.
    // Return only exact matches. Unknown identifiers must return no entity.
    return []
  }

  func ${camelName}Entities(matching string: String) async throws -> [${typeName}] {
    // TODO: Resolve a spoken or typed name against user-approved records.
    // Match display names case-insensitively; an unknown name must return no entity.
    return []
  }

  func suggested${entity.swiftName}Entities() async throws -> [${typeName}] {
    // TODO: Return only user-approved, searchable application records.
    return []
  }
}

@MainActor
enum IntentLane${entity.swiftName}Integration {
  static func register() {
    IntentLaneEntityResolvers.${entity.id} = ${implementationName}()
  }

  static func index(_ entities: [${typeName}]) async throws {
    // Call after a committed create or update, not merely when the app launches.
    try await CSSearchableIndex(name: ${swiftString(`${ir.app.id}.${entity.id}`)}).indexAppEntities(entities)
  }

  static func remove(identifiers: [String]) async throws {
    // Call with the exact stable identifiers when records become unavailable.
    try await CSSearchableIndex(name: ${swiftString(`${ir.app.id}.${entity.id}`)}).deleteAppEntities(identifiedBy: identifiers, ofType: ${typeName}.self)
  }
}`;
  });
  const searchBlocks = searches.map((intent) => {
    const handler = nativeHandlerName(intent);
    return `actor IntentLane${intent.swiftName}Implementation: ${handler} {
  func perform(criteria: StringSearchCriteria) async throws {
    // TODO: Route the existing in-app search UI with criteria.term.
    // Do not open a record here: a query with no exact match must open nothing.
  }
}

@MainActor
enum IntentLane${intent.swiftName}Integration {
  static func register() {
    IntentLaneIntentHandlers.${intent.id} = IntentLane${intent.swiftName}Implementation()
  }
}`;
  });
  const openBlocks = opens.map((intent) => {
    const entity = targetEntity(ir, intent);
    const typeName = `IntentLane${entity.swiftName}Entity`;
    const handler = openHandlerName(intent);
    return `actor IntentLane${intent.swiftName}Implementation: ${handler} {
  func perform(target: ${typeName}) async throws {
    // TODO: Navigate to the exact application record represented by target.id.
    // Run UI work on the main actor. If target.id is unknown or unavailable, throw;
    // never substitute a similarly named record or silently open a generic screen.
  }
}

@MainActor
enum IntentLane${intent.swiftName}Integration {
  static func register() {
    IntentLaneIntentHandlers.${intent.id} = IntentLane${intent.swiftName}Implementation()
  }
}`;
  });
  return `// IntentLane adapter template. This file belongs to the application; fill the TODOs and keep it out of generated output.\n// It deliberately contains no App Shortcuts registration.\n\nimport AppIntents\nimport CoreSpotlight\nimport Foundation\n\n${[...blocks, ...openBlocks, ...searchBlocks].join("\n\n")}\n`;
}

export function generatedFileHash(contents: string): string {
  return createHash("sha256").update(contents).digest("hex");
}

function stringsQuoted(value: string): string {
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  return `"${escaped}"`;
}

function stringsEntries(ir: ConfigIR, locale: string): readonly (readonly [string, string])[] {
  const fallback = defaultLocale(ir);
  const entries = new Map<string, string>();
  const consider = (values: LocalizedText | undefined): void => {
    if (!values) return;
    const key = localized(values, fallback);
    const translation = localized(values, locale);
    if (key.length === 0 || translation === key || entries.has(key)) return;
    entries.set(key, translation);
  };
  for (const entity of ir.entities) consider(entity.title);
  for (const intent of ir.intents) {
    consider(intent.title);
    consider(intent.description);
    consider(intent.risk?.confirmationPrompt);
    consider(intent.dialog);
    for (const parameter of intent.parameters) {
      consider(parameter.title);
      consider(parameter.prompt);
      for (const labels of Object.values(parameter.values ?? {})) consider(labels);
    }
  }
  return [...entries.entries()];
}

export function generateStrings(ir: ConfigIR, locale: string): string {
  const lines = stringsEntries(ir, locale).map(([key, value]) => `${stringsQuoted(key)} = ${stringsQuoted(value)};`);
  return lines.length === 0 ? `${STRINGS_BANNER}\n` : `${STRINGS_BANNER}\n${lines.join("\n")}\n`;
}

export type GeneratedArtifact = Readonly<{ path: string; contents: string }>;

const comparePaths = (left: string, right: string): number => (left < right ? -1 : left > right ? 1 : 0);

export function generateArtifacts(ir: ConfigIR): readonly GeneratedArtifact[] {
  const fallback = defaultLocale(ir);
  const artifacts: GeneratedArtifact[] = [{ path: GENERATED_SWIFT_FILE, contents: generateSwift(ir) }];
  for (const locale of ir.app.locales) {
    if (locale === fallback) continue;
    artifacts.push({ path: `${locale}.lproj/${STRING_TABLE}.strings`, contents: generateStrings(ir, locale) });
  }
  return artifacts.sort((left, right) => comparePaths(left.path, right.path));
}
