import { createHash } from "node:crypto";
import type { ConfigIR, IntentIR, LocalizedText, ParameterIR } from "../../core/src/index.js";

export const GENERATED_SWIFT_FILE = "IntentLaneGenerated.swift";
export const STRING_TABLE = "IntentLane";

const STRINGS_BANNER = "/* Generated by IntentLane. Do not edit. */";

const swiftString = (value: string): string => JSON.stringify(value);
const shortcutPhrase = (value: string): string => swiftString(value).replace(/\$\{appName\}/g, "\\(.applicationName)");
const defaultLocale = (ir: ConfigIR): string => ir.app.locales[0] ?? "en";
const localized = (values: LocalizedText, locale: string): string => values[locale] ?? values[Object.keys(values).sort()[0] ?? ""] ?? "";
const localizedResource = (value: string): string => `LocalizedStringResource(${swiftString(value)}, table: ${swiftString(STRING_TABLE)})`;

function parameterDeclaration(parameter: ParameterIR): string {
  if (parameter.type !== "string") throw new Error(`IL1301: Parameter '${parameter.id}' uses unsupported Phase 1 type '${parameter.type}'.`);
  return `  @Parameter(title: ${localizedResource(parameter.id)})\n  var ${parameter.id}: String`;
}

function routeExpression(intent: IntentIR, scheme: string): string {
  const entries = Object.entries(intent.mapping).sort(([left], [right]) => left.localeCompare(right));
  if (entries.length === 0) return `IntentLaneRoute.make(scheme: ${swiftString(scheme)}, path: ${swiftString(intent.route)}, query: [:])`;
  const items = entries.map(([target, source]) => `${swiftString(target)}: ${source}`).join(", ");
  return `IntentLaneRoute.make(scheme: ${swiftString(scheme)}, path: ${swiftString(intent.route)}, query: [${items}])`;
}

function emitIntent(intent: IntentIR, locale: string, scheme: string): string {
  const title = localized(intent.title, locale);
  const description = intent.description ? `\n  static let description = IntentDescription(${localizedResource(localized(intent.description, locale))})` : "";
  const parameters = intent.parameters.map(parameterDeclaration).join("\n\n");
  const dialog = intent.dialog ? localized(intent.dialog, locale) : title;
  return `struct ${intent.swiftName}: AppIntent {\n  static let title: LocalizedStringResource = ${localizedResource(title)}${description}\n\n${parameters}\n\n  func perform() async throws -> some IntentResult & ProvidesDialog & OpensIntent {\n    let url = ${routeExpression(intent, scheme)}\n    return .result(opensIntent: OpenURLIntent(url), dialog: IntentDialog(${localizedResource(dialog)}))\n  }\n}`;
}

function emitShortcuts(ir: ConfigIR, locale: string): string {
  const registered = ir.intents
    .map((intent) => ({ intent, phrases: intent.phrases[locale] ?? [] }))
    .filter(({ phrases }) => phrases.length > 0);
  if (registered.length === 0) return "";
  const providers = registered.map(({ intent, phrases }) => `      AppShortcut(intent: ${intent.swiftName}(), phrases: [\n${phrases.map((phrase) => `        ${shortcutPhrase(phrase)}`).join(",\n")}\n      ], shortTitle: ${localizedResource(localized(intent.title, locale))}, systemImageName: "sparkles")`);
  return `struct IntentLaneShortcuts: AppShortcutsProvider {\n  static var appShortcuts: [AppShortcut] {\n${providers.join("\n")}\n  }\n}`;
}

export function generateSwift(ir: ConfigIR): string {
  const locale = defaultLocale(ir);
  const intents = ir.intents.map((intent) => emitIntent(intent, locale, ir.app.urlScheme)).join("\n\n");
  const shortcuts = emitShortcuts(ir, locale);
  const shortcutsSection = shortcuts ? `\n\n${shortcuts}` : "";
  return `// Generated by IntentLane. Do not edit.\n// Source schema: ${ir.schemaVersion}\n\nimport AppIntents\nimport Foundation\n\nenum IntentLaneRoute {\n  static func make(scheme: String, path: String, query: [String: String]) -> URL {\n    var components = URLComponents()\n    components.scheme = scheme\n    components.path = path\n    components.queryItems = query.sorted { $0.key < $1.key }.map { URLQueryItem(name: $0.key, value: $0.value) }\n    return components.url ?? URL(string: "about:blank")!\n  }\n}\n\n${intents}${shortcutsSection}\n`;
}

export function generatedFileHash(contents: string): string {
  return createHash("sha256").update(contents).digest("hex");
}

function stringsQuoted(value: string): string {
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  return `"${escaped}"`;
}

function stringsEntries(ir: ConfigIR, locale: string): readonly (readonly [string, string])[] {
  const fallback = defaultLocale(ir);
  const entries = new Map<string, string>();
  const consider = (values: LocalizedText | undefined): void => {
    if (!values) return;
    const key = localized(values, fallback);
    const translation = localized(values, locale);
    if (key.length === 0 || translation === key || entries.has(key)) return;
    entries.set(key, translation);
  };
  for (const intent of ir.intents) {
    consider(intent.title);
    consider(intent.description);
    consider(intent.dialog);
  }
  return [...entries.entries()];
}

export function generateStrings(ir: ConfigIR, locale: string): string {
  const lines = stringsEntries(ir, locale).map(([key, value]) => `${stringsQuoted(key)} = ${stringsQuoted(value)};`);
  return lines.length === 0 ? `${STRINGS_BANNER}\n` : `${STRINGS_BANNER}\n${lines.join("\n")}\n`;
}

export type GeneratedArtifact = Readonly<{ path: string; contents: string }>;

const comparePaths = (left: string, right: string): number => (left < right ? -1 : left > right ? 1 : 0);

export function generateArtifacts(ir: ConfigIR): readonly GeneratedArtifact[] {
  const fallback = defaultLocale(ir);
  const artifacts: GeneratedArtifact[] = [{ path: GENERATED_SWIFT_FILE, contents: generateSwift(ir) }];
  for (const locale of ir.app.locales) {
    if (locale === fallback) continue;
    artifacts.push({ path: `${locale}.lproj/${STRING_TABLE}.strings`, contents: generateStrings(ir, locale) });
  }
  return artifacts.sort((left, right) => comparePaths(left.path, right.path));
}
