#!/bin/bash
# Assembles IntentLaneStudio.app next to the engine and the pilot manifests, so the
# window runs the same TypeScript engine the CLI does and loads the same
# manifests. Nothing here installs anything or touches the user's system.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
package="$(dirname "$here")"
repo="$(cd "$package/../.." && pwd)"

swift build --package-path "$package" -c release
binary="$(swift build --package-path "$package" -c release --show-bin-path)/IntentLaneStudio"

app="$package/build/IntentLaneStudio.app"
mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"

cp "$binary" "$app/Contents/MacOS/IntentLaneStudio"
cp "$package/Resources/Info.plist" "$app/Contents/Info.plist"
# No .lproj is copied: the window writes its labels inline and the bundle declares
# no localization, so a strings table here would be a promise nobody reads.
# `AppSurfaceTests` fails if a declared language ever comes back without strings
# the views use, or if a strings file returns without a declared language.

# The engine the window drives, bundled rather than resolved from a path, so the
# app cannot silently run a different engine than the one it was built with.
mkdir -p "$app/Contents/Resources/engine" "$app/Contents/Resources/pilots"
cp "$repo/packages/cli/dist/index.cjs" "$app/Contents/Resources/engine/index.cjs"

# The engine is a Node bundle, so it needs an executable to point at. A wrapper
# is what makes the window's `executableURL` honest: it runs this exact bundle,
# with this exact Node, and cannot resolve some other intentlane from PATH.
node_bin="$(command -v node)"
cat > "$app/Contents/Resources/engine/run" <<LAUNCHER
#!/bin/sh
# Generated by Scripts/build-app.sh. Do not edit; rebuild instead.
exec "$node_bin" "$app/Contents/Resources/engine/index.cjs" "\$@"
LAUNCHER
chmod +x "$app/Contents/Resources/engine/run"
cp -R "$repo/pilots/." "$app/Contents/Resources/pilots/"

echo "built $app"
