#!/bin/bash
# Assembles IntentLaneStudio.app next to the engine and the pilot manifests, so the
# window runs the same TypeScript engine the CLI does and loads the same
# manifests. Nothing here installs anything or touches the user's system.
#
# The bundle is assembled beside the final one and swapped in when it is complete,
# so a build that fails leaves the previous bundle intact rather than a half-written
# one, and so a resource deleted from the sources cannot survive inside a bundle
# that was assembled before the deletion. `BundleAssemblyTests` checks that
# property against the assembler, not against this script.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
package="$(dirname "$here")"
repo="$(cd "$package/../.." && pwd)"

swift build --package-path "$package" -c release
binary="$(swift build --package-path "$package" -c release --show-bin-path)/IntentLaneStudio"

app="$package/build/IntentLaneStudio.app"
# A fresh staging directory, so the bundle that is swapped in carries exactly the
# resources this run copied. Reusing the previous directory is how a deleted
# resource used to survive.
#
# The assembler is pointed at the `.app` inside the temp directory, not at the
# temp directory itself: the assembler refuses to write into a directory that
# exists, and `mktemp -d` has already made one.
staging_root="$(mktemp -d "${TMPDIR:-/tmp}/intentlane-studio-bundle.XXXXXX")"
staging="$staging_root/IntentLaneStudio.app"
trap 'rm -rf "$staging_root"' EXIT

# The engine is a Node bundle, so it needs an executable to point at. A wrapper
# is what makes the window's `executableURL` honest: it runs this exact bundle,
# with this exact Node, and cannot resolve some other intentlane from PATH.
node_bin="$(command -v node)"

# The wrapper names the bundle's final path, not its staging path, so it still
# works after the swap.
cat > "$staging_root/run" <<LAUNCHER
#!/bin/sh
# Generated by Scripts/build-app.sh. Do not edit; rebuild instead.
exec "$node_bin" "$app/Contents/Resources/engine/index.cjs" "\$@"
LAUNCHER

INTENTLANE_STUDIO_APP="$staging" \
INTENTLANE_STUDIO_BINARY="$binary" \
INTENTLANE_STUDIO_PACKAGE="$package" \
INTENTLANE_STUDIO_REPO="$repo" \
INTENTLANE_STUDIO_LAUNCHER="$staging_root/run" \
  node "$here/assemble-bundle.mjs"

# Swap only once the staged bundle is complete. The previous bundle moves aside
# first, so `mv` never has to move a directory onto a non-empty one. The staging
# root is removed only after the move, since it is the bundle's parent until then.
previous="$app.previous"
[ -e "$previous" ] && rm -rf "$previous"
[ -e "$app" ] && mv "$app" "$previous"
mv "$staging" "$app"
trap - EXIT
rm -rf "$staging_root"
[ -e "$previous" ] && rm -rf "$previous"

echo "built $app"
