#!/bin/bash
# Assembles IntentLaneStudio.app next to the engine and the pilot manifests, so the
# window runs the same TypeScript engine the CLI does and loads the same
# manifests. Nothing here installs anything or touches the user's system.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
package="$(dirname "$here")"
repo="$(cd "$package/../.." && pwd)"

swift build --package-path "$package" -c release
binary="$(swift build --package-path "$package" -c release --show-bin-path)/IntentLaneStudio"

app="$package/build/IntentLaneStudio.app"
mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"

cp "$binary" "$app/Contents/MacOS/IntentLaneStudio"
cp "$package/Resources/Info.plist" "$app/Contents/Info.plist"
mkdir -p "$app/Contents/Resources/en.lproj" "$app/Contents/Resources/fr.lproj"
cp "$package/Resources/en.lproj/Localizable.strings" "$app/Contents/Resources/en.lproj/Localizable.strings"
cp "$package/Resources/fr.lproj/Localizable.strings" "$app/Contents/Resources/fr.lproj/Localizable.strings"

# The engine the window drives, bundled rather than resolved from a path, so the
# app cannot silently run a different engine than the one it was built with.
mkdir -p "$app/Contents/Resources/engine" "$app/Contents/Resources/pilots"
cp "$repo/packages/cli/dist/index.cjs" "$app/Contents/Resources/engine/index.cjs"

# The engine is a Node bundle, so it needs an executable to point at. A wrapper
# is what makes the window's `executableURL` honest: it runs this exact bundle,
# with this exact Node, and cannot resolve some other intentlane from PATH.
node_bin="$(command -v node)"
cat > "$app/Contents/Resources/engine/run" <<LAUNCHER
#!/bin/sh
# Generated by Scripts/build-app.sh. Do not edit; rebuild instead.
exec "$node_bin" "$app/Contents/Resources/engine/index.cjs" "\$@"
LAUNCHER
chmod +x "$app/Contents/Resources/engine/run"
cp -R "$repo/pilots/." "$app/Contents/Resources/pilots/"

echo "built $app"
